services:
  - type: web
    name: telegram-music-bot
    env: python
    plan: free
    buildCommand: "apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: OWNER_ID
        sync: false
      - key: SUDO_USERS
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: DURATION_LIMIT_MIN
        value: "120"
